spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  
  spotify:
    api-base-url: https://api.spotify.com/v1
    polling-interval-seconds: 5
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    redirect-uri: ${SPOTIFY_REDIRECT_URI}

logging:
  level:
    com.theradio: INFO
    org.springframework: WARN

spring:
  datasource:
    hikari:
      initialization-fail-timeout: 0
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC